// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieqvzndvkzozqvseubuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImllcXZ6bmR2a3pvenF2c2V1YnVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQzMTcxMjQsImV4cCI6MjA5OTg5MzEyNH0.jmdbbYj3PkeRwVvkxqcCcczjDt6RSeFQa_qRW6NU3jQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});